#!/bin/bash

useradd -s /bin/bash -m node
touch /home/node/.bash_profile
chown node:node /home/node/.bash_profile
install -o node -g node -d -m 0755 /home/node/bin

curl https://raw.githubusercontent.com/creationix/nvm/v0.6.1/install.sh > /tmp/install-nvm.sh
chmod 0755 /tmp/install-nvm.sh
chown node:node /tmp/install-nvm.sh

sudo -i -u node /tmp/install-nvm.sh
sudo -i -u node nvm install v0.11.12
sudo -i -u node nvm alias default v0.11.12
